print ("")
input1 = float(input ("Give me number one  "))
input2 = float(input ("Give me number two "))
input3 = float(input ("Give me number three "))
input4 = float(input ("Give me number four  "))
input5 = float(input ("Give me number five  "))
input6 = int(input ("Give me number six "))
input7 = int(input ("Give me number seven "))
input8 = int(input ("Give me number eight  "))
input9 = int(input ("Give me number nine "))
input10 = int(input ("Give me number ten  "))

print ("")
print ("Fourth output: ", (input4)//(input2))
print ("Fifth output: ", (input2)%(input1))
print ("Sixth output: ", (input2)-(input3))
print ("Seventh output: ", (input2)**(input3))
print ("Output: ", (input10)/(input2))
print ("Second output: ", (input4)*(input2))
print ("Third output: ", (input1)+(input8))
print ("Fourth output: ", (input4)//(input2))
print ("Fifth output: ", (input2)%(input1))
print ("Sixth output: ", (input9)-(input3))
print ("Seventh output: ", (input2)**(input10))
print ("Output: ", (input1)/(input2))
print ("Second output: ", (input4)*(input2))
print ("Third output: ", (input1)+(input3))
print ("Fourth output: ", (input4)//(input2))
print ("Fifth output: ", (input2)%(input1))
print ("Sixth output: ", (input2)-(input3))
print ("Seventh output: ", (input2)**(input3))
print ("Output: ", (input10)/(input2))
print ("Second output: ", (input4)*(input2))
print ("Third output: ", (input1)+(input8))
print ("Fourth output: ", (input4)//(input2))
print ("Fifth output: ", (input2)%(input1))
print ("Sixth output: ", (input9)-(input3))
print ("Seventh output: ", (input2)**(input10))
print ("Output: ", (input1)/(input2))
print ("Second output: ", (input4)*(input2))
print ("Third output: ", (input1)+(input3))
print ("Fourth output: ", (input4)//(input2))
print ("Fifth output: ", (input2)%(input1))
print ("Sixth output: ", (input2)-(input3))
print ("Seventh output: ", (input2)**(input3))
print ("Output: ", (input10)/(input2))
print ("Second output: ", (input4)*(input2))
print ("Third output: ", (input1)+(input8))
print ("Fourth output: ", (input4)//(input2))
print ("Fifth output: ", (input2)%(input1))
print ("Sixth output: ", (input9)-(input3))
print ("Seventh output: ", (input2)**(input10))
print ("This is our output: ", (input1)/(input2), (input4)*(input2), (input1)+(input3), (input1)+(input3))
print ("")